### ISSUE TITLE
about dataset and DetectorFreeSfM

### ISSUE THREAD

**Issue by luoww1992** [zju3dv/LoG#10]
i  have see DetectorFreeSfM, 
![image](https://github.com/zju3dv/LoG/assets/45957595/c76e8210-fda5-412b-8008-cd9a86e01df1)

i know that Colmap-generated *.bin outputs
but how to get the  args in blue part form video?
1, need GPS ? if True, how to do ?
2, if only video, some default args from video ?

**Comment by chingswy** [comment]
Please check here.
