### ISSUE TITLE
GUI shows “LoG is not responding”

### ISSUE THREAD

**Issue by Gaozihui** [zju3dv/LoG#17]
Hi, I have train the model. Also the 4090 runs check_gui.py correctly. However, when I tried the order python3 apps/gui.py filename=config/example/test/train.yml ckptname=output/example/test/log/model_latest.pth, I got a stuck gui showing nothing.

![LoG](https://github.com/zju3dv/LoG/assets/58518515/a08efdf7-f874-4d67-9835-8af28b360bfd)

Do you have any idea about that?
Thanks a lot.

**Comment by chingswy** [comment]
Just wait. Loading the checkpoint can take a considerable amount of time.

**Comment by Gaozihui** [comment]
Ok thanks, I will try. Just keep clicking WAIT right?

**Comment by chingswy** [comment]
Fixed.
