### ISSUE TITLE
Test script error

### ISSUE THREAD

**Issue by hecodeit** [zju3dv/LoG#2]
Run apps/test_dataset.py, show:
```
File "/workspace/LoG/apps/test_dataset.py", line 25, in <module>
print('image shape: ', data['image'].shape)
AttributeError: 'str' object has no attribute 'shape'
```

Run apps/test_pointcloud.py, show:
```
File "/workspace/LoG/apps/test_pointcloud.py", line 24, in <module>
from LoG.model.base_gaussian import BaseGaussian
ModuleNotFoundError: No module named 'LoG.model.base_gaussian'
```

**Comment by chingswy** [comment]
Thank you for your feedback. I have re-uploaded the test data and revised the corresponding code. If the issue persists, please let me know, and I'll continue to investigate.

**Comment by hecodeit** [comment]
Thank you for your reply; I'm waiting for the code update.
