### ISSUE TITLE
.ply export

### ISSUE THREAD

**Issue by arlo-ml** [zju3dv/LoG#7]
Hi,
do you have any plan to support a .ply export, compatible with the .ply files that can be viewed by 3dgs, so that we can check point-based radiance field rendering using other apps like Unity?

**Comment by chingswy** [comment]
Thank you for reaching out. We will support .ply export in the future. However, unfortunately, due to our rendering mechanisms differing from the original 3dgs, the exported results will not be compatible with the LOD (Level of Detail) mechanisms in other apps like Unity.
